[package]
name = "dioxus-spring"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
async-channel = "1.9.0"
dioxus = "0.4.0"
dioxus-web = "0.4.0"
futures = "0.3.28"
interpolation = "0.3.0"
js-sys = "0.3.64"
wasm-bindgen = "0.2.87"
web-sys = "0.3.64"
